### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [seanpianka/Zipcodes#9]
It appears that the manifest is missing at least one file necessary to build from the sdist for version 1.1.0. You're in good company, about 5% of other projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary zipcodes -w /tmp/ext zipcodes==1.1.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting zipcodes==1.1.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/ed3/fa4e01acd5c00/zipcodes-1.1.0.tar.gz (718 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-mqwpiu1l/zipcodes/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-mqwpiu1l/zipcodes/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-mqwpiu1l/zipcodes/pip-egg-info
         cwd: /tmp/pip-wheel-mqwpiu1l/zipcodes/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-mqwpiu1l/zipcodes/setup.py", line 7, in <module>
        with open("VERSION.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by junjaytan** [comment]
Hi Sean, any chance you can accept thatch's PR? This is an issue for me too. Thanks!

**Comment by seanpianka** [comment]
Thanks for the help and your code contribution!
